version: '2.4'

services:
  postgresql:
    container_name: postgresql
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-postgresql}
      TZ: ${TZ-America/Sao_Paulo}
    volumes:
       - ./files2docker/scripts:/scripts
       - ${LOCAL_PGDATA-./files2docker/databases}:/var/lib/postgresql/data
       - ${BACKUP_PATH-./files2docker/backup}:/backup
    ports:
      - ${POSTGRES_PORT-5432}:5432
    restart: unless-stopped
